# -*- coding: utf-8 -*-
"""cold_email_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6wUvecJfZkPH-v0pMizoRpDEmPK4S2h

## Imports
"""

import pandas as pd
import gspread
from google.colab import auth
from google.auth import default
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import os

from __future__ import annotations

import csv

from typing import Iterable, Optional

import requests

import httpx
import openai
from openai import OpenAI

import json

try:
    from google.colab import userdata
except ImportError:
    userdata = None

"""## Constants"""

file_path = '/content/drive/MyDrive/Shortbreak/Vertrieb/Leads/sb_cm_input.gsheet'
sheet_name="input"
BASE_URL = "https://api.hunter.io/v2"
PROMPT = """Recherchiere zunächst das Unternehmen unter {domain} im Web.

Schreibe anschließend eine personalisierte E-Mail an {last_name} (Anrede passend zu: {gender}).
Orientiere dich stark an der Struktur und dem Tonfall dieser Vorlage verwende wenn möglich jedoch unternehmensspezifischen Bezug in der Mail:

--- VORLAGE ---
{template}
--- ENDE VORLAGE ---

Gib mir das Ergebnis in folgendem Shema zurück und gib mir nur dieses Schema zurück kein weiterer prosatext{"subject":subject,"text":text}"""
PROMPT_FIELDS = ("domain", "last_name", "gender", "template")

# Logical field -> column name in the source DataFrame
DEFAULT_COLUMN_MAPPING = {
    "domain": "domaine",
    "last_name": "last_name",
    "gender": "gender",
    "template": "template",
}

"""## Load Input Excel"""

def get_sheet_data_by_path(file_path, sheet_name='Sheet1'):
    """
    Loads a Google Sheet document by extracting its name from a given file path
    (assuming the file path points to a .gsheet shortcut file) and returns it
    as a pandas DataFrame.

    Args:
        file_path (str): The path to the .gsheet shortcut file in Google Drive.
                         Example: '/content/drive/MyDrive/Folder/YourSheet.gsheet'
        sheet_name (str): The name of the worksheet to load (e.g., 'Sheet1', 'Tabelle1').
                          Defaults to 'Sheet1'.

    Returns:
        pandas.DataFrame: A DataFrame containing the data from the specified worksheet,
                          or None if an error occurs.
    """
    # 1. Authenticate with Google Colab
    auth.authenticate_user()

    # 2. Authorize gspread to access your Google Drive/Sheets
    try:
        creds, _ = default()
        gc = gspread.authorize(creds)
    except Exception as e:
        print(f"Error during gspread authorization: {e}")
        return None

    # 3. Extract the Google Sheet's document name from the file_path
    # .gsheet files are shortcuts and cannot be opened directly from the filesystem.
    # We extract the base name and assume it's the title of the Google Sheet.
    base_name = os.path.basename(file_path) # e.g., 'sb_cm_input.gsheet'
    doc_name = os.path.splitext(base_name)[0] # e.g., 'sb_cm_input'

    if not doc_name:
        print(f"Error: Could not extract document name from file path: {file_path}")
        return None

    # 4. Open the Google Sheet by its title (document name)
    try:
        spreadsheet = gc.open(doc_name)
    except gspread.exceptions.SpreadsheetNotFound:
        print(f"Error: Google Sheet with title '{doc_name}' not found. Please ensure the name is correct and you have access.")
        return None
    except Exception as e:
        print(f"An error occurred while opening the spreadsheet: {e}")
        return None

    # 5. Select a worksheet
    try:
        worksheet = spreadsheet.worksheet(sheet_name)
    except gspread.exceptions.WorksheetNotFound:
        print(f"Error: Worksheet '{sheet_name}' not found in the spreadsheet. Available worksheets are: {[ws.title for ws in spreadsheet.worksheets()]}")
        return None
    except Exception as e:
        print(f"An error occurred while selecting the worksheet: {e}")
        return None

    # 6. Get all data as a list of lists
    data = worksheet.get_all_values()

    # 7. Convert to a Pandas DataFrame
    if data:
        df = pd.DataFrame(data[1:], columns=data[0]) # Assuming the first row is the header
        print("DataFrame created successfully:")
        print(df.head())
        return df.to_dict('records')
    else:
        print(f"No data found in the worksheet '{sheet_name}'.")
        return pd.DataFrame() # Return empty DataFrame if no data

"""## Call Hunter API"""

"""Hunter.io Email Finder wrapper — accepts a company name or a domain.

Docs: https://hunter.io/api-documentation/v2#email-finder
"""

def _get(endpoint: str, params: dict, api_key: Optional[str], timeout: int = 15) -> dict:
    api_key = None
    if userdata is not None:
    # Achtung: userdata.get() nimmt kein Default-Argument und wirft
    # bei fehlendem Secret eine Exception, statt None zurückzugeben.
      try:
          api_key = userdata.get("HUNTER_MSA")
      except Exception:
          api_key = None
    if not api_key:
        raise ValueError("No API key: pass api_key= or set HUNTER_API_KEY.")

    response = requests.get(
        f"{BASE_URL}/{endpoint}",
        params={**params, "api_key": api_key},
        timeout=timeout,
    )

    if response.status_code != 200:
        body = response.json() if response.content else {}
        errors = body.get("errors", [{}])
        raise RuntimeError(
            f"Hunter {endpoint} error {response.status_code}: "
            f"{errors[0].get('details', response.text)}"
        )

    return response.json()


def resolve_domain(
    company: str,
    api_key: Optional[str] = None,
    perfect_match: bool = True,
) -> Optional[str]:
    """Resolve a company name to its most likely domain (Domain Finder, free).

    perfect_match=True returns only high-similarity matches, so you get one
    confident answer instead of a candidate list. Returns None if unresolved.
    """
    if len(company) < 3:
        raise ValueError("Domain Finder requires at least 3 characters.")

    data = _get(
        "domain-finder",
        {"company": company, "limit": 1, "perfect_match": str(perfect_match).lower()},
        api_key,
    ).get("data", [])

    return data[0]["domain"] if data else None


def find_email(
    first_name: str,
    last_name: str,
    company: str,
    api_key: Optional[str] = None,
    resolve_first: bool = True,
) -> dict:
    """Look up a work email for a person at a company.

    `company` may be a plain company name ("Stripe") or a domain
    ("stripe.com"). With resolve_first=True, a company name is first sent
    through the free Domain Finder so the lookup runs against an explicit
    domain — more accurate, and you can see which domain was used.

    Returns: email, domain, score, position, verification_status,
    source_count, resolved_domain. `email` is None when nothing is found.
    """
    looks_like_domain = "." in company and " " not in company
    params = {"first_name": first_name, "last_name": last_name}
    resolved = None

    if looks_like_domain:
        params["domain"] = company
    elif resolve_first:
        resolved = resolve_domain(company, api_key)
        # Fall back to Hunter's own conversion if the name doesn't resolve.
        if resolved:
            params["domain"] = resolved
        else:
            params["company"] = company
    else:
        params["company"] = company
    if not resolved:
      return {
        "email": "Not in Hunter",
        "domain": "Not in Hunter",
        "score": "Not in Hunter",
        "position": "Not in Hunter",
        "verification_status": "Not in Hunter",
        "source_count": "Not in Hunter",
        "resolved_domain": "Not in Hunter",
    }
    data = _get("email-finder", params, api_key).get("data", {})

    return {
        "email": data.get("email"),
        "domain": data.get("domain"),
        "score": data.get("score"),
        "position": data.get("position"),
        "verification_status": (data.get("verification") or {}).get("status"),
        "source_count": len(data.get("sources", [])),
        "resolved_domain": resolved,
    }


def find_emails_to_csv(
    people: Iterable[tuple[str, str, str]],
    path: str = "emails.csv",
    api_key: Optional[str] = None,
) -> str:
    """Run find_email over (first_name, last_name, company) tuples and write
    email + domain to a CSV. Failures are recorded per row, not raised."""
    fields = [
        "first_name", "last_name", "company",
        "email", "domain", "score", "verification_status", "error",
    ]

    with open(path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()

        for first, last, company in people:
            row = {"first_name": first, "last_name": last, "company": company}
            try:
                result = find_email(first, last, company, api_key)
                row.update({k: v for k, v in result.items() if k in fields})
            except Exception as exc:  # network error, rate limit, bad key
                row["error"] = str(exc)
            writer.writerow(row)

    return path

#result = find_email("Melanie", "Rickert", "Buchholz Hydraulik",api_key="ac5e384905798ea0e600a27b5295554e4bda71c0")

#result

#merged = [ i|r for i,r in zip(input_data,[result])]#input_data[1] | result
#merged

"""## Resolve Template"""

def read_google_doc_content(drive_path: str) -> str:
    """
    Liest den Inhalt eines Google Docs-Dokuments, das durch seinen Drive-Pfad angegeben ist,
    und gibt ihn als einfachen String zurück.

    Args:
        drive_path (str): Der vollständige Pfad zum Google Docs-Dokument in Google Drive,
                          z.B. '/content/drive/MyDrive/MyFolder/MyDocument.gdoc'.
                          Die Funktion extrahiert den Basisnamen (ohne .gdoc-Erweiterung)
                          als Dokumenttitel, um in Drive zu suchen.

    Returns:
        str: Der reine Textinhalt des Google Docs-Dokuments.

    Raises:
        ValueError: Wenn das Dokument nicht gefunden oder nicht zugegriffen werden kann.
        HttpError: Für andere Google API-Fehler.
    """
    # Benutzer authentifizieren
    auth.authenticate_user()
    credentials, _ = default()

    # Drive API-Dienst erstellen
    drive_service = build('drive', 'v3', credentials=credentials)

    # Dokumenttitel aus dem Pfad extrahieren
    doc_title = os.path.splitext(os.path.basename(drive_path))[0]

    file_id = None
    try:
        # Suche nach Dateien mit dem exakten Namen und Google Docs mimeType
        # 'application/vnd.google-apps.document'
        query = f"name='{doc_title}' and mimeType='application/vnd.google-apps.document'"
        results = drive_service.files().list(q=query, fields="files(id, name)").execute()
        items = results.get('files', [])

        if not items:
            raise ValueError(f"Google Docs-Dokument '{doc_title}' in Drive nicht gefunden.")
        elif len(items) > 1:
            print(f"Warnung: Mehrere Google Docs mit dem Titel '{doc_title}' gefunden. Verwende das erste gefundene (ID: {items[0]['id']}).")

        file_id = items[0]['id']

    except HttpError as error:
        raise ValueError(f"Fehler bei der Suche nach Dokument '{doc_title}': {error}") from error

    if not file_id:
        raise ValueError(f"Konnnte keine Datei-ID für Dokument '{doc_title}' ermitteln.")

    # Inhalt des Dokuments als reinen Text exportieren
    try:
        request = drive_service.files().export(fileId=file_id, mimeType='text/plain')
        content_bytes = request.execute()
        content_string = content_bytes.decode('utf-8')
        return content_string
    except HttpError as error:
        raise ValueError(f"Fehler beim Exportieren des Inhalts für Dokument-ID '{file_id}': {error}") from error

template_a=read_google_doc_content("/content/drive/MyDrive/Shortbreak/Vertrieb/Leads/Template_A.gdoc")
template_b=read_google_doc_content("/content/drive/MyDrive/Shortbreak/Vertrieb/Leads/Template_B.gdoc")

templates={"A":template_a,"B":template_b}

"""## Create Prompt"""

def build_prompt(
    prompt_template: str,
    input_dict:dict,
    strict: bool = True,
    mail_template: str = None,
) -> str:
    """Substitute {domain}, {name}, {gender} and {mail_template} into the template.

    Deliberately uses str.replace instead of str.format: mail templates often
    contain their own curly braces, which .format() would treat as placeholders
    and reject with KeyError or ValueError.
    """
    values = {
        "domain": input_dict["domain"],
        "last_name": input_dict["last_name"],
        "gender": input_dict["gender"],
        "template": mail_template,
    }

    if strict:
        missing = [f for f in PROMPT_FIELDS if "{" + f + "}" not in prompt_template]
        if missing:
            raise ValueError(
                "Placeholders missing from prompt template: "
                + ", ".join("{" + f + "}" for f in missing)
            )

    result = prompt_template
    for key, value in values.items():
        result = result.replace("{" + key + "}", str(value))
    return result

"""## Draft Email"""

class RetryableOpenAIAPIError(Exception):
    """OpenAI-API-Fehler, bei dem ein erneuter Versuch sinnvoll ist."""


class NonRetryableOpenAIAPIError(Exception):
    """OpenAI-API-Fehler, bei dem ein erneuter Versuch nicht sinnvoll ist."""


def _resolve_api_key(api_key: str | None = None) -> str:
    if api_key:
        return api_key
    if userdata is not None:
        # Achtung: userdata.get() nimmt kein Default-Argument und wirft
        # bei fehlendem Secret eine Exception, statt None zurückzugeben.
        try:
            api_key = userdata.get("OPENAI_API_KEY")
        except Exception:
            api_key = None
    api_key = api_key or os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise NonRetryableOpenAIAPIError(
            "OpenAI API-Schlüssel nicht gefunden. Bitte als 'OPENAI_API_KEY' im "
            "Colab-Geheimnis-Manager hinterlegen oder direkt übergeben."
        )
    return api_key


def _extract_text(response) -> str:
    # Bequemer Weg: das SDK aggregiert alle Text-Blöcke selbst.
    text = getattr(response, "output_text", None)
    if text:
        return text

    # Fallback: manuell über die Output-Items laufen.
    parts = []
    for entry in getattr(response, "output", []):
        if getattr(entry, "type", None) != "message":
            continue
        content = entry.content
        if isinstance(content, str):
            parts.append(content)
        else:
            for chunk in content:
                if getattr(chunk, "type", None) == "output_text":
                    chunk_text = getattr(chunk, "text", None)
                    if chunk_text:
                        parts.append(chunk_text)
    return "\n".join(parts)


def call_openai_with_web_search(
    prompt: str,
    api_key: str | None = None,
    model: str = "gpt-5.6-luna",
    max_tokens: int = 10000,
) -> str:
    key = _resolve_api_key(api_key)

    try:
        with OpenAI(api_key=key) as client:
            response = client.responses.create(
                model=model,
                input=prompt,
                tools=[{"type": "web_search"}],
                max_output_tokens=max_tokens,
            )
        return _extract_text(response)

    except openai.RateLimitError as e:
        raise RetryableOpenAIAPIError(f"Rate Limit überschritten: {e}") from e
    except openai.APIStatusError as e:
        status = e.status_code
        if 500 <= status < 600:
            raise RetryableOpenAIAPIError(f"Serverfehler ({status}): {e}") from e
        raise NonRetryableOpenAIAPIError(f"Clientfehler ({status}): {e}") from e

    except openai.APITimeoutError as e:
        raise RetryableOpenAIAPIError(f"Timeout-Fehler: {e}") from e
    except openai.APIConnectionError as e:
        raise RetryableOpenAIAPIError(f"Verbindungsfehler: {e}") from e

    # Falls httpx direkt durchschlägt (z. B. eigener http_client).
    except (httpx.ConnectError, httpx.TimeoutException) as e:
        raise RetryableOpenAIAPIError(f"Verbindungs-/Timeout-Fehler: {e}") from e
    except httpx.RequestError as e:
        raise RetryableOpenAIAPIError(f"Netzwerkfehler: {e}") from e
    except Exception as e:
        raise NonRetryableOpenAIAPIError(f"Unerwarteter Fehler: {e}") from e

"""## Create Draft"""

import imaplib
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
def create_draft(user_entry:dict):
  # --- KONFIGURATION ---
  IMAP_SERVER = "imap.mailbox.org"
  IMAP_PORT = 993
  USERNAME = ""  # Ihre mailbox.org E-Mail-Adresse
  PASSWORD = ""              # Ihr Passwort (oder App-Passwort)

  # --- E-MAIL INHALT ERSTELLEN ---
  msg = MIMEMultipart("alternative")
  msg["Subject"] = user_entry["subject"]
  msg["From"] = USERNAME
  msg["To"] = user_entry["email"]

  # Standard-E-Mail-Fußzeile definieren (Platzhalter)
  mail_footer_text = ""

  mail_footer_html = """
  <div class="default-style io-ox-signature" style="font-size:15px; font-family:-apple-system,BlinkMacSystemFont,helvetica,sans-serif;">
    <div class="default-style">&nbsp;</div>
    <div class="default-style">&nbsp;</div>
    <div class="default-style">&nbsp;</div>
    <div class="default-style">
      <span style="font-size: 13pt;"><img id="72796faa-e584-47f2-b6bf-90d6b3d29f7a" class="aspect-ratio" style="width: 51px; height: 51px; max-width: 100%;" src="/appsuite/api/image/mail/picture?folder=default0%2FDrafts&amp;id=42263&amp;uid=72796faa-e584-47f2-b6bf-90d6b3d29f7a" alt="" width="51" height="51"><strong></strong></span>
    </div>
    <div class="default-style">
      <span style="font-size: 12pt;"><strong>newcon GmbH&nbsp;</strong></span>
    </div>
    <div class="default-style">
      <div class="default-style">
      <div>
        <span style="font-weight: 400; font-size: 8pt;"><a href="http://www.newcon.info" target="_blank" rel="noopener">www.newcon.info</a><a href="http://www.newcon.info" target="_blank" rel="noopener">&nbsp;</a></span>
      </div>
      <div>
        <span style="font-weight: 400; font-size: 8pt;"><a href="mailto:kontakt@newcon.info" class="mailto-link" target="_blank">kontakt@newcon.info</a></span>
      </div>
      <div class="default-style" style="font-family: -apple-system, BlinkMacSystemFont, helvetica, sans-serif;">&nbsp;</div>
      <div>
        <span style="font-weight: 400; font-size: 8pt;">Schießrain 32&nbsp;</span>
      </div>
      <div>
        <span style="font-weight: 400; font-size: 8pt;">77652 Offenburg</span>
      </div>
      <div>
        <span style="font-weight: 400; font-size: 8pt;">T +49 1577 9472074</span>
      </div>
      <div>&nbsp;</div>
      <div class="default-style">
        <div>
        <span style="font-size: 8pt;"><span style="font-weight: 400;">Amtsgericht Freiburg </span><span style="font-weight: 400;">HRB 723481</span></span>
        </div>
        <div class="default-style">
        <div>
          <span style="font-size: 8pt;"><strong>Geschäftsführung:</strong><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;">Niklas Bühler, Philipp Kreit</span></span>
        </div>
        <div>&nbsp;</div>
        </div>
        <div>&nbsp;</div>
      </div>
      </div>
      <div>&nbsp;</div>
    </div>
    </div>
  """

  # Reiner Text als Fallback
  text_content = user_entry["text"] + mail_footer_text
  print(text_content)
  # template_a in HTML umwandeln (Ersetzen von Newlines durch <br> Tags)
  html_main_content = "<p>" + text_content.replace('\n', '<br>') + "</p>"
  print(html_main_content)
  # Das gewünschte HTML-Design
  html_content = f"""
  <html>
    <body>
      {html_main_content}
      {mail_footer_html}
    </body>
  </html>
  """

  msg.attach(MIMEText(text_content, "plain", "utf-8"))
  msg.attach(MIMEText(html_content, "html", "utf-8"))

  # --- PER IMAP ALS ENTWURF SPECHERN ---
  try:
      # 1. Verbindung zum SSL-Server aufbauen
      mail = imaplib.IMAP4_SSL(IMAP_SERVER, IMAP_PORT)
      mail.login(USERNAME, PASSWORD)

      # 2. E-Mail in Byte-String umwandeln
      raw_message = msg.as_bytes()

      # 3. Den Entwurf in den Ordner "Drafts" hochladen
      # mailbox.org nutzt standardmäßig den Ordnernamen "Drafts"
      # Die Option r'(\Draft)' markiert die Mail im System als Entwurf
      folder = "Drafts"
      flags = r"(\Draft)"
      date_time = imaplib.Time2Internaldate(time.time())

      status, response = mail.append(folder, flags, date_time, raw_message)

      if status == "OK":
          print(f"Erfolgreich! Der HTML-Entwurf wurde im Ordner '{folder}' gespeichert.")
      else:
          print(f"Fehler beim Speichern: {response}")

      # 4. Verbindung sauber trennen
      mail.logout()

  except Exception as e:
      print(f"Ein Fehler ist aufgetreten: {e}")

#create_draft(user_entry)

"""## Save results"""

import pandas as pd
import gspread
from google.colab import auth
from google.auth import default
import os
from datetime import datetime
import re
from zoneinfo import ZoneInfo
import math
import gspread.utils # Import this for A1 notation conversions

CELL_CHAR_LIMIT = 50_000      # Google Sheets limit per cell
SHEET_NAME_LIMIT = 100        # Google Sheets limit per tab name
INVALID_SHEET_CHARS = r"[\\[\\]:*?/\\]"


def get_gspread_client() -> gspread.Client:
    """Authenticate the current Colab user and return a gspread client.

    Triggers the OAuth popup on first call in a session.
    """
    auth.authenticate_user()
    credentials, _ = default()
    return gspread.authorize(credentials)


def make_timestamp_name(
    prefix: str = "",
    timezone: str = "Europe/Berlin",
    fmt: str = "%Y-%m-%d_%H-%M-%S",
) -> str:
    """
    Build a worksheet name from the current time.

    Colons and slashes are not allowed in sheet names, so the default format
    uses hyphens instead.
    """
    stamp = datetime.now(ZoneInfo(timezone)).strftime(fmt)
    name = f"{prefix}{stamp}" if prefix else stamp
    name = re.sub(INVALID_SHEET_CHARS, "-", name)
    return name[:SHEET_NAME_LIMIT]


def _to_cell_value(value):
    """Convert a pandas value into something the Sheets API accepts."""
    if value is None:
        return ""
    if isinstance(value, float) and math.isnan(value):
        return ""
    try:
        if pd.isna(value):  # catches pd.NA and pd.NaT
            return ""
    except (TypeError, ValueError):
        pass

    if isinstance(value, float):
        return value
    if isinstance(value, (bool, int)):
        return value
    text = value if isinstance(value, str) else str(value)
    if len(text) > CELL_CHAR_LIMIT:
        return text[: CELL_CHAR_LIMIT - 3] + "..."
    return text


def write_dicts_to_new_timestamp_sheet(
    data_list: list[dict],
    google_sheets_path: str,
    name_prefix: str = "output_",
    timezone: str = "Europe/Berlin",
    freeze_header: bool = True,
) -> tuple[str, str]:
    """
    Writes a list of dictionaries as rows to a new worksheet in a Google Sheet.
    The new worksheet is named with the current timestamp.

    Args:
        data_list (list[dict]): A list of dictionaries, where each dictionary
                                represents a row to be written.
        google_sheets_path (str): The path to the .gsheet shortcut file in Google Drive.
                                  This path is used to identify the target Google Spreadsheet
                                  by its title (filename without extension).
        name_prefix (str): Optional prefix for the new sheet name (e.g., "output_").
        timezone (str): IANA zone used for the timestamp in the sheet name.
        freeze_header (bool): If True, the header row will be frozen.

    Returns:
        tuple[str, str]: A tuple containing the name of the new sheet and its URL.

    Raises:
        ValueError: If the data_list is empty or the Google Sheet cannot be found/accessed.
        gspread.exceptions.SpreadsheetNotFound: If the spreadsheet is not found.
        Exception: For other errors during Google API operations.
    """
    if not data_list:
        raise ValueError("The data_list is empty, nothing to write.")

    # Convert list of dictionaries to DataFrame
    df = pd.DataFrame(data_list)

    # Get gspread client (authenticates user)
    client = get_gspread_client()

    # Extract the Google Sheet's document name from the file_path
    # This assumes the .gsheet file name (without extension) is the actual title of the Google Sheet
    base_name = os.path.basename(google_sheets_path)
    doc_name = os.path.splitext(base_name)[0]

    if not doc_name:
        raise ValueError(f"Could not extract document name from file path: {google_sheets_path}")

    spreadsheet_obj = None
    try:
        # Open the spreadsheet by its title
        spreadsheet_obj = client.open(doc_name)
    except gspread.exceptions.SpreadsheetNotFound:
        raise gspread.exceptions.SpreadsheetNotFound(
            f"Google Sheet with title '{doc_name}' not found. "
            "Please ensure the name is correct and you have access."
        )
    except Exception as e:
        raise Exception(f"An error occurred while opening the spreadsheet: {e}") from e

    # Generate a unique sheet name with a timestamp
    new_sheet_base_name = make_timestamp_name(prefix=name_prefix, timezone=timezone)
    sheet_name = new_sheet_base_name
    existing_sheet_titles = {ws.title for ws in spreadsheet_obj.worksheets()}
    counter = 1
    while sheet_name in existing_sheet_titles:
        counter += 1
        sheet_name = f"{new_sheet_base_name}_{counter}"
        if len(sheet_name) > SHEET_NAME_LIMIT:
            # Prevent infinite loop or very long names if prefix is too long
            sheet_name = f"{new_sheet_base_name[:SHEET_NAME_LIMIT-len(str(counter))-1]}_{counter}"

    # Add the new worksheet
    worksheet = spreadsheet_obj.add_worksheet(
        title=sheet_name,
        rows=len(df) + 1, # +1 for header row
        cols=len(df.columns),
    )

    # Prepare data for writing
    header = [str(c) for c in df.columns]
    rows = [[_to_cell_value(v) for v in row] for row in df.itertuples(index=False)]

    # Write data to the worksheet
    worksheet.update(values=[header] + rows, range_name="A1")

    # Format header
    if freeze_header:
        worksheet.freeze(rows=1)
        worksheet.format("A1:Z1", {"textFormat": {"bold": True}})

    # Construct the URL to the new sheet
    url = f"{spreadsheet_obj.url}#gid={worksheet.id}"
    return sheet_name, url

def apply_conditional_formatting_to_column(
    spreadsheet_url_or_id: str,
    sheet_name: str,
    column_name: str,
    condition_type: str, # e.g., 'NUMBER_GREATER', 'NUMBER_LESS', 'NUMBER_BETWEEN', 'TEXT_CONTAINS', etc.
    color_rgb: dict, # e.g., {'red': 1.0, 'green': 0.0, 'blue': 0.0, 'alpha': 1.0}
    threshold_value: float | str | None = None, # can be float for numbers, string for text
    threshold_value2: float | str | None = None, # for BETWEEN condition
    client: gspread.Client | None = None,
):
    """
    Applies conditional formatting to a specified column in a Google Sheet.

    Args:
        spreadsheet_url_or_id (str): The URL or ID of the Google Spreadsheet.
        sheet_name (str): The name of the worksheet to apply formatting to.
        column_name (str): The name of the column to format.
        condition_type (str): The type of condition (e.g., 'NUMBER_GREATER', 'NUMBER_LESS', 'TEXT_CONTAINS').
                              See Google Sheets API documentation for valid types.
        color_rgb (dict): A dictionary specifying the RGB color, e.g., {'red': 1.0, 'green': 0.0, 'blue': 0.0}.
                          Values should be between 0.0 and 1.0. An 'alpha' key can also be included.
        threshold_value (float | str | None): The primary value for the condition.
        threshold_value2 (float | str | None): The secondary value for 'NUMBER_BETWEEN' or 'TEXT_BETWEEN' conditions.
        client (gspread.Client | None): An existing gspread client. If None, one will be created.
    """
    client = client or get_gspread_client()

    if spreadsheet_url_or_id.startswith("http"):
        # Extract the base URL without the #gid part
        base_spreadsheet_url = spreadsheet_url_or_id.split('#')[0]
        book = client.open_by_url(base_spreadsheet_url)
    else:
        book = client.open_by_key(spreadsheet_url_or_id)

    worksheet = book.worksheet(sheet_name)

    # Get column index from header row
    headers = worksheet.row_values(1)
    try:
        col_index_0_based = headers.index(column_name)  # 0-based column index
    except ValueError:
        raise ValueError(f"Column '{column_name}' not found in sheet '{sheet_name}'.")

    condition_values = []
    if threshold_value is not None:
        condition_values.append({'userEnteredValue': str(threshold_value)})
    if threshold_value2 is not None:
        condition_values.append({'userEnteredValue': str(threshold_value2)})

    # Construct the Sheets API request body for adding a conditional format rule
    request_body = {
        'addConditionalFormatRule': {
            'rule': {
                'ranges': [{
                    'sheetId': worksheet.id,
                    'startRowIndex': 1,  # Apply from the second row (after header)
                    'endRowIndex': worksheet.row_count, # To the end of the sheet
                    'startColumnIndex': col_index_0_based,
                    'endColumnIndex': col_index_0_based + 1  # End is exclusive
                }],
                'booleanRule': {
                    'condition': {
                        'type': condition_type,
                        'values': condition_values
                    },
                    'format': {
                        'backgroundColor': color_rgb
                    }
                }
            },
            'index': 0  # Add at the top, so it has highest priority
        }
    }

    # Perform the batch update
    book.batch_update({'requests': [request_body]})
    print(f"Bedingte Formatierung erfolgreich auf Spalte '{column_name}' im Blatt '{sheet_name}' angewendet.")

#write_dicts_to_new_timestamp_sheet(data_list=[user_entry],google_sheets_path=file_path)

"""## Pipeline"""

def run_mail_pipeline():
  # Get data from "CRM"
  input_data = get_sheet_data_by_path(file_path, sheet_name=sheet_name)

  #Enrich data using Hunter
  hunter_data=[find_email(first_name=entry["first_name"],
                          last_name=entry["last_name"],
                          company=entry["company"])
                          for entry in input_data]

  # Add Hunter data to original input
  hunter_and_input=[ i|r for i,r in zip(input_data,hunter_data)]

  # Generate Hunter based prompt
  enriched_prompt =[]
  for entry in hunter_and_input:
    entry.update({"prompt":build_prompt(prompt_template=PROMPT,
                                        input_dict=entry,
                                        mail_template=
                                        templates[entry["template"]])})
    enriched_prompt.append(entry)

  # Call LLM to generate Mail and Subject
  enriched_draft=[]
  for entry in enriched_prompt:
    mail_content=call_openai_with_web_search(entry["prompt"])
    enriched_draft.append(json.loads(mail_content))

  # Merge LLM response to data and create drafts
  user_entries = [org|update for org,update in zip(enriched_prompt,enriched_draft)]
  for user_entry in user_entries:
    create_draft(user_entry)

  # Save processed data to google sheets
  sheets_name, sheets_url = write_dicts_to_new_timestamp_sheet(data_list=user_entries, google_sheets_path=file_path)

run_mail_pipeline()

fiusfhosfao

"""## Pipeline step by step"""

sheets_name, sheets_url = write_dicts_to_new_timestamp_sheet(data_list=[user_entry], google_sheets_path=file_path)

# Beispiel: Bedingte Formatierung für die Spalte 'score'
# Grün, wenn der Score >= 90 ist
apply_conditional_formatting_to_column(
    spreadsheet_url_or_id=sheets_url,
    sheet_name=sheets_name,
    column_name='score',
    condition_type='NUMBER_GREATER', # Korrigiert zu 'NUMBER_GREATER'
    color_rgb={'red': 0.8, 'green': 1.0, 'blue': 0.8}, # Helles Grün
    threshold_value=89, # Angepasst, um Werte >= 90 zu erfassen (größer als 89)
)

# Rot, wenn der Score < 90 ist
apply_conditional_formatting_to_column(
    spreadsheet_url_or_id=sheets_url,
    sheet_name=sheets_name,
    column_name='score',
    condition_type='NUMBER_LESS', # Korrigiert zu 'NUMBER_LESS'
    color_rgb={'red': 1.0, 'green': 0.8, 'blue': 0.8}, # Helles Rot
    threshold_value=90, # Angepasst, um Werte < 90 zu erfassen (kleiner als 90)
)

print(f"Bedingte Formatierung auf '{sheets_name}' in {sheets_url} angewendet.")

# Get data from "CRM"
input_data = get_sheet_data_by_path(file_path, sheet_name=sheet_name)
input_data

entry=input_data[-1]
d=find_email(first_name=entry["first_name"],
                        last_name=entry["last_name"],
                        company=entry["company"])
d

#Enrich data using Hunter
hunter_data=[find_email(first_name=entry["first_name"],
                        last_name=entry["last_name"],
                        company=entry["company"])
                        for entry in input_data]
hunter_data

# Add Hunter data to original input
hunter_and_input=[ i|r for i,r in zip(input_data,hunter_data)]
hunter_and_input

# Generate Hunter based prompt
enriched_prompt =[]
for entry in hunter_and_input:
  entry.update({"prompt":build_prompt(prompt_template=PROMPT,
                                      input_dict=entry,
                                      mail_template=
                                      templates[entry["template"]])})
  enriched_prompt.append(entry)
enriched_prompt

# Call LLM to generate Mail and Subject
enriched_draft=[]
for entry in enriched_prompt:
  mail_content=call_openai_with_web_search(entry["prompt"])
  enriched_draft.append(json.loads(mail_content))
enriched_draft

# Merge LLM response to data and create drafts
user_entries = [org|update for org,update in zip(enriched_prompt,enriched_draft)]
for user_entry in user_entries:
  create_draft(user_entry)
user_entries

# Save processed data to google sheets
sheets_name, sheets_url = write_dicts_to_new_timestamp_sheet(data_list=user_entries, google_sheets_path=file_path)